services:
  claims-tracker:
    image: ghcr.io/thikade/claim-tracker:latest
    build: .
    ports:
      - "8081:8080"
    volumes:
      # - claims-data:/app/data
      - ./data:/app/data
    restart: unless-stopped

# volumes:
#   claims-data:
