services:
  claims-tracker:
    image: claims-tracker
    build: .
    ports:
      - "8081:8080"
    volumes:
      # - claims-data:/app/data
      - ./data-docker:/app/data
    restart: unless-stopped

# volumes:
#   claims-data:
